version: "3"

networks:
  internal:

services:
  click-meet:
    container_name: click-meet
    restart: always
    build: './click-meet'
    ports:
      - "2137:2137"
    links:
      - users-microservice
      - availability-microservice
      - interests-microservice
    networks:
      internal:
        aliases:
          - click-meet

  users-microservice:
    container_name: users-microserice
    restart: always
    build: './users-microservice'
    ports:
      - "8080:8080"
    links:
      - mongo-users
      - redis
    networks:
      internal:
        aliases:
          - users-microservice

  availability-microservice:
    container_name: availability-microserice
    restart: always
    build: './availability-microservice'
    ports:
      - "9010:9010"
    links:
      - mongo-availability
      - redis
    networks:
      internal:
        aliases:
          - availability-microservice

  interests-microservice:
    container_name: interests-microserice
    restart: always
    build: './interests-microservice'
    ports:
      - "9020:9020"
    links:
      - mongo-interests
      - redis
    networks:
      internal:
        aliases:
          - interests-microservice

  mongo-interests:
    container_name: mongo-interests
    image: mongo
    networks:
      internal:
        aliases:
          - mongo-interests

  mongo-availability:
    container_name: mongo-availability
    image: mongo
    networks:
      internal:
        aliases:
          - mongo-availability

  mongo-users:
    container_name: mongo-users
    image: mongo
    networks:
      internal:
        aliases:
          - mongo-users
          
  redis:
    container_name: redis
    image: redis
    networks:
      internal:
        aliases:
          - redis