version: "3"

networks:
  internal:

services:
  users-microservice:
    container_name: users-microserice
    restart: always
    build: './users-microservice'
    ports:
      - "8080:8080"
    links:
      - mongo-users
      - redis
    networks:
      internal:
        aliases:
          - users-microservice

  availability-microservice:
    container_name: availability-microserice
    restart: always
    build: './availability-microservice'
    ports:
      - "9010:9010"
    links:
      - mongo-availability
      - redis
    networks:
      internal:
        aliases:
          - availability-microservice

  mongo-availability:
    container_name: mongo-availability
    image: mongo
    networks:
      internal:
        aliases:
          - mongo-availability

  mongo-users:
    container_name: mongo-users
    image: mongo
    networks:
      internal:
        aliases:
          - mongo-users
          
  redis:
    container_name: redis
    image: redis
    networks:
      internal:
        aliases:
          - redis